config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cars#index"
  resources :cars, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  get "dashboard", to: "profiles#dashboard"
  get "dashboard-my-car", to: "profiles#my_car"
  get "dashboard-booking", to: "profiles#booking"
  delete "dashboard-booking/:id", to: "profiles#destroy_booking", as: "destroy_booking"
  post "dashboard-booking/:id/accept", to: "profiles#accept_request", as: "accept_request"
  post "dashboard-booking/:id/decline", to: "profiles#decline_request", as: "decline_request"
  get 'payment', to: "pages#payment"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :kilometers, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many_attached :photos
  belongs_to :user
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode

  validates :brand, presence: true
  validates :model, presence: true
  validates :horsepower, presence: true, numericality: { only_integer: true }, length: { maximum: 4 }
  validates :year, presence: true
  validates :kilometers, presence: true, numericality: { only_integer: true }, length: { maximum: 6 }
  validates :plate, presence: true, length: { maximum: 10 }, uniqueness: true
  validates :energy, presence: true
  validates :seats, presence: true, numericality: { only_integer: true }, length: { maximum: 2 }
  validates :user_id, presence: true
  validates :price, presence: true, numericality: { only_integer: true }, length: { maximum: 4 }

  private

  def address
    "#{user.street}, #{user.city}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :bookings, dependent: :destroy
  has_many :cars, through: :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  validates :birthday, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :license, presence: true
  validates :street, presence: true
  validates :postal_code, presence: true

  private

  def article_params
    params.require(:user).permit(:avatar)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    if session[:params] && session[:params]["calendar"]
      session[:previous_url] || root_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,
                                                       :street, :city, :country, :username, :birthday, :postal_code, :phone, :license, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:street, :city, :postal_code, :phone])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
    if session[:params] && session[:params]["calendar"]
      @start_date = session[:params]["calendar"].split[0]
      @end_date = session[:params]["calendar"].split[2]
    else
      @start_date = params[:calendar].split[0]
      @end_date = params[:calendar].split[2]
    end
    @kilometers = params[:kilometers] || session[:params]["kilometers"].to_i
    @comment = params[:comment] || session[:params]["comment"]
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.car = @car
    if @booking.save
      redirect_to payment_path
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :kilometers, :user_id, :comment)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "brand ILIKE :query OR model ILIKE :query"
      @cars = Car.where(sql_query, query: "%#{params[:query]}%")
    else
      @cars = Car.all
    end
  end

  def show
    @car = Car.find(params[:id])
    @unavailability = []
    @car.bookings.where("status ILIKE 'accepted' OR status ILIKE 'pending_payment'").each do |i|
      @unavailability << { from: i.start_date.strftime("%Y-%m-%d"), to: i.end_date.strftime("%Y-%m-%d") }
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(params_validate)
    @car.user = current_user
    if @car.save
      redirect_to dashboard_my_car_path
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(params_validate)
    if @car.save
      redirect_to dashboard_my_car_path
    else
      render :edit
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to dashboard_my_car_path
  end

  private

  def params_validate
    params.require(:car).permit(:brand, :model, :year, :horsepower,
                                :kilometers, :plate, :energy, :seats, :smoker, :animals, :color, :price, :description, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def payment
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def dashboard
  end

  def my_car
    @my_cars = Car.where(user_id: current_user.id)
  end

  def booking
    @my_bookings = Booking.where(user_id: current_user.id)
    my_cars = Car.where(user_id: current_user.id)
    @my_cars_bookings = Booking.where(car_id: my_cars.ids)
  end

  def destroy_booking
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_booking_path
  end

  def accept_request
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    redirect_to dashboard_booking_path
  end

  def decline_request
    @booking = Booking.find(params[:id])
    @booking.update(status: "declined")
    redirect_to dashboard_booking_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1554223090-7e482851df45?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1703);">
  <div class="container">
    <h2>Vérifiez votre réservation</h2>
  </div>
</div>
<div class="container mb-5 review my-3">
  <h3>Vérifiez votre réservation</h3>
  <div class="row">
    <div class="col-6 input-field my-3">
      <%= simple_form_for [ @car, @booking ] do |f| %>
        <%= f.input :start_date, as: :string, html5: true, input_html: { :value => @start_date}, readonly: true %>
        <%= f.input :end_date, as: :string, html5: true, input_html: { :value => @end_date}, readonly: true %>
        <%= f.input :comment, input_html: { :value => @comment} %>
        <%= f.input :kilometers, as: :string, input_html: { :value => @kilometers}, readonly: true %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="price-calculated d-flex justify-content-between border-bottom">
          <% days = (Date.parse(@end_date) - Date.parse(@start_date)).to_i %>
          <p><%= @car.price %> x <%= days %> jours</p>
          <p><%= (@car.price * days) %>€</p>
        </div>
        <div class="total-price d-flex justify-content-between my-3">
          <h5>Total</h5>
          <p><%= (@car.price * days) + @kilometers.to_i * (@car.price / 1000) %>€</p>
        </div>
      </div>
      <div class="col-6 align-self-center text-center">
        <div class="review-card">
          <% if @car.photos.length > 0 %>
            <%= cl_image_tag @car.photos[0].key, class:'review-card-img', id: "review-car-img"%>
          <% else %>
            <img src="https://cdn.motor1.com/images/mgl/nGzgl/s1/2021-bugatti-chiron-front.jpg" id="review-car-img" class="review-card-img">
          <% end %>
          <div class="review-card-content p-3">
            <h5><%= @car.brand %> <%= @car.model %></h5>
            <p><%= @car.description %></p>
            <div class="spec d-flex justify-content-between m-3">
              <p><%= @car.horsepower %>hp</p>
              <p><%=@car.energy %></p>
              <% if @car.seats > 1 %>
                <p><%= @car.seats %> places</p>
              <% else %>
                <p><%= @car.seats %> place</p>
              <% end %>
            </div>
            <div id="recap-price">
              <h4><%= @car.price%>€ / jours</span></h4>
          </div>
        </div>
      </div>
      <button type="button" class='btn btn-secondary' id='cancel-btn'><%= link_to 'Annuler', root_path %></button>
      <%= f.submit "Reserver maintenant", class: "my-3 btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cars/index.html.erb
<div class="container mt-5 custom-footer">
  <div class="row">
    <div class="col-md-12 d-flex justify-content-between">
      <h3 class="car-counter">Voitures (<%= @cars.count %>)</h3>
    </div>
  </div>
<div class="row row-cols-1 row-cols-md-3 g-4 my-2">
  <% @cars.each do |car| %>
    <div class="col">
      <div class="card">
        <% if car.photos.length > 0 %>
          <%= cl_image_tag car.photos[0].key, class:'card-img-top', id: "car-img"%>
        <% else %>
          <img src="https://cdn.motor1.com/images/mgl/nGzgl/s1/2021-bugatti-chiron-front.jpg" id="car-img" class="card-img-top">
        <% end %>
        <div class="card-body">
          <div class="card-header d-flex justify-content-between">
            <h3><%= car.brand %> <%= car.model %></h3>
          </div>
          <p class="card-text"><%= car.description %></p>
          <div class="spec d-flex justify-content-between m-3">
            <p><%= car.horsepower %>hp</p>
            <p><%= car.energy %></p>
            <% if car.seats > 1 %>
              <p><%= car.seats %> places</p>
            <% else %>
              <p><%= car.seats %> place</p>
            <% end %>
          </div>
          <div class="price d-flex justify-content-between">
            <h4><%= car.price%>€/<span class="days"> jours</span></h4>
            <%= link_to 'Voir plus', car_path(car), class: "see-more"%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/booking.html.erb
<div class="dashboard">
  <div class="row">
    <div class="col-3 sidebar">
      <%= link_to root_path, class: "navbar-brand mt-5" do %>
        <h1>Wheelz</h1>
      <% end %>
      <p><%= link_to "Profil", dashboard_path %></p>
      <hr>
      <p><%= link_to "My cars", dashboard_my_car_path %></p>
      <hr>
      <p><%= link_to "Bookings", dashboard_booking_path, class: "active"  %></p>
    </div>
    <div class="col-9 dashboard-content">
      <div class="container header d-flex justify-content-between my-3">
        <h3>Dashboard</h3>
        <div class="avatar-menu d-flex">
          <p><%= current_user.first_name %> <%= current_user.last_name %></p>
          <ul class="user-profil">
            <li class="nav-item dropdown">
              <% if current_user.avatar.key.nil? %>
                <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgsaRe2zqH_BBicvUorUseeTaE4kxPL2FmOQ&usqp=CAU", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Home", root_path, class: "dropdown-item" %>
                <%= link_to "Disconnect", destroy_user_session_path, method:'delete', class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="container body-content dashboard-body my-3">
        <div class="d-flex justify-content-between">
          <div>
            <h4>Réservation pour mes voitures</h4>
          </div>
        </div>
        <table class="table mt-3">
          <thead>
            <tr>
              <th scope="col">Détails de la réservation</th>
              <th scope="col">Nom du client</th>
              <th scope="col">Date de début</th>
              <th scope="col">Date de fin</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            <% @my_cars_bookings.each do |booking| %>
              <% if booking.status == 'pending_payment' %>
                <tr>
                  <td><%= booking.car.brand %> <%= booking.car.model%></td>
                  <td><%= booking.user.first_name %> <%= booking.user.last_name %></td>
                  <td><%= booking.start_date %></td>
                  <td><%= booking.end_date %></td>
                  <% if booking.status == "accepted" %>
                    <td>
                      <p>En attente paiement</p>
                    </td>
                    <td>
                      <%= link_to destroy_booking_path(booking), method: 'delete' do %>
                        <i class="fas fa-solid fa-trash iframe-red"></i>
                      <% end %>
                    </td>
                  <% end%>
                  <td>
                    <%= link_to accept_request_path(booking), method: 'post' do %>
                      <i class="fas fa-check iframe-green"></i>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to decline_request_path(booking), method: 'post' do %>
                      <i class="fas fa-ban iframe-red"></i>
                    <% end %>
                  </td>
                </tr>
              <% else %>
                <tr>
                  <td><%= booking.car.brand %> <%= booking.car.model%></td>
                  <td><%= booking.user.first_name %> <%= booking.user.last_name %></td>
                  <td><%= booking.start_date %></td>
                  <td><%= booking.end_date %></td>
                  <% if booking.status == "pending_payment" %>
                    <td>
                      <p>En attente paiement</p>
                    </td>
                    <td>
                      <%= link_to destroy_booking_path(booking), method: 'delete' do %>
                        <i class="fas fa-solid fa-trash iframe-red"></i>
                      <% end %>
                    </td>
                  <% elsif booking.status == "accepted"%>
                    <td>
                      <p>Accepté</p>
                    </td>
                    <td>
                      <%= link_to destroy_booking_path(booking), method: 'delete' do %>
                        <i class="fas fa-solid fa-trash iframe-red"></i>
                      <% end %>
                    </td>
                  <% else %>
                    <td>
                      <p>Refusé</p>
                    </td>
                    <td>
                      <%= link_to destroy_booking_path(booking), method: 'delete' do %>
                        <i class="fas fa-solid fa-trash iframe-red"></i>
                      <% end %>
                    </td>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="container body-content dashboard-body my-3">
        <div class="d-flex justify-content-between">
          <div>
            <h4>Mes réservations</h4>
          </div>
        </div>
        <table class="table mt-3">
          <thead>
            <tr>
              <th scope="col">Détails de la réservation</th>
              <th scope="col">Nom du propriétaire</th>
              <th scope="col">Date de début</th>
              <th scope="col">Date de fin</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            <% @my_bookings.each do |booking| %>
              <tr>
                <td><%= booking.car.brand %> <%= booking.car.model%></td>
                <td><%= booking.car.user.first_name %> <%= booking.car.user.last_name %></td>
                <td><%= booking.start_date %></td>
                <td><%= booking.end_date %></td>
                <% if booking.status == "pending_payment" %>
                  <td>
                    <p>En attente paiement</p>
                  </td>
                  <td>
                    <%= link_to destroy_booking_path(booking), method: 'delete' do %>
                      <i class="fas fa-solid fa-trash iframe-red"></i>
                    <% end %>
                  </td>
                <% elsif booking.status == "accepted"%>
                  <td>
                    <p>Accepté</p>
                  </td>
                  <td>
                    <%= link_to destroy_booking_path(booking), method: 'delete' do %>
                      <i class="fas fa-solid fa-trash iframe-red"></i>
                    <% end %>
                  </td>
                <% else %>
                  <td>
                    <p>Refusé</p>
                  </td>
                  <td>
                    <%= link_to destroy_booking_path(booking), method: 'delete' do %>
                      <i class="fas fa-solid fa-trash iframe-red"></i>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

app/views/profiles/dashboard.html.erb
<div class="dashboard">
  <div class="row">
    <div class="col-3 sidebar">
      <%= link_to root_path, class: "navbar-brand mt-5" do %>
        <h1>Wheelz</h1>
      <% end %>
      <p><%= link_to "Profil", dashboard_path, class: "active"  %></p>
      <hr>
      <p><%= link_to "My cars", dashboard_my_car_path %></p>
      <hr>
      <p><%= link_to "Bookings", dashboard_booking_path %></p>
    </div>
    <div class="col-9 dashboard-content">
      <div class="container header d-flex justify-content-between my-3">
        <h3>Dashboard</h3>
        <div class="avatar-menu d-flex">
          <p><%= current_user.first_name %> <%= current_user.last_name %></p>
          <ul class="user-profil">
            <li class="nav-item dropdown">
              <% if current_user.avatar.key.nil? %>
                <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgsaRe2zqH_BBicvUorUseeTaE4kxPL2FmOQ&usqp=CAU", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
              <% else %>
                <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Home", root_path, class: "dropdown-item" %>
                <%= link_to "Disconnect", destroy_user_session_path, method:'delete', class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="container body-content dashboard-body my-3">
        <div>
          <h4>Votre profil</h4>
          <hr>
        </div>
        <div class="d-flex justify-content-evenly">
          <div>
            <ul>
              <li>Prénom : <span class="light-li"><%= current_user.first_name %></span></li>
              <li>Nom de famille : <span class="light-li"><%= current_user.last_name %></span></li>
              <li>Username : <span class="light-li"><%= current_user.username %></span></li>
              <li>Email : <span class="light-li"><%= current_user.email %></span></li>
              <li>Date d'anniversaire : <span class="light-li"><%= current_user.birthday %></span></li>
              <li>Rue : <span class="light-li"><%= current_user.street %></span></li>
              <li>Ville : <span class="light-li"><%= current_user.city %></span></li>
              <li>Code postal : <span class="light-li"><%= current_user.postal_code %></span></li>
              <li>Pays : <span class="light-li"><%= current_user.country %></span></li>
            </ul>
          </div>
          <div class="profil mt-4">
            <h5>Photo de profil</h5>
            <div class="mt-3 mb-3">
              <% if current_user.avatar.key.nil? %>
                <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgsaRe2zqH_BBicvUorUseeTaE4kxPL2FmOQ&usqp=CAU", class:"avatar-profil"%>
              <% else %>
                <%= cl_image_tag current_user.avatar.key %>
              <% end %>
            </div>
            <%= link_to 'Modify profil', edit_user_registration_path(current_user), class: "button-dashboard" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/my_car.html.erb
<div class="dashboard">
  <div class="row">
    <div class="col-3 sidebar">
      <%= link_to root_path, class: "navbar-brand mt-5" do %>
        <h1>Wheelz</h1>
      <% end %>
      <p><%= link_to "Profil", dashboard_path %></p>
      <hr>
      <p><%= link_to "My cars", dashboard_my_car_path, class: "active"  %></p>
      <hr>
      <p><%= link_to "Bookings", dashboard_booking_path %></p>
    </div>
    <div class="col-9 dashboard-content">
      <div class="container header d-flex justify-content-between my-3">
        <h3>Dashboard</h3>
        <div class="avatar-menu d-flex">
          <p><%= current_user.first_name %> <%= current_user.last_name %></p>
          <ul class="user-profil">
            <li class="nav-item dropdown">
              <% if current_user.avatar.key.nil? %>
                <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgsaRe2zqH_BBicvUorUseeTaE4kxPL2FmOQ&usqp=CAU", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Home", root_path, class: "dropdown-item" %>
                <%= link_to "Disconnect", destroy_user_session_path, method:'delete', class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="container body-content dashboard-body my-3">
        <div class="d-flex justify-content-between">
          <div>
            <h4>Mes voiture(s)</h4>
          </div>
          <div>
            <p><%= link_to "Voiture +",  new_car_path, class: "button-dashboard-car" %></p>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Infos voiture</th>
              <th scope="col">Date d'ajout</th>
              <th scope="col">Disponibilité</th>
            </tr>
          </thead>
          <tbody>
            <% @my_cars.each do |car| %>
              <tr>
                <td><%= car.brand %> <%= car.model %> | <%= car.plate%></td>
                <td><%= car.created_at %></td>
                <td><%= car.status %></td>
                <td>
                  <%= link_to edit_car_path(car.id) do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                </td>
                <td>
                  <%= link_to car_path(car), :method => 'delete', class: "iframe-red" do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1>Wheelz</h1>
    <% end %>
    <div class="search-bar">
      <%= simple_form_for :search, url: root_path, method: :get do |f| %>
        <div class="search-form-control form-group">
          <%= form_tag cars_path, method: :get do %>
            <%= text_field_tag :query, params[:query], class: "form-control search-placeholder", id: "search_query", placeholder: "Search"%>
          <% end %>
          <button type="submit" class="btn btn-flat search-logo">
            <i class="fas fa-search"></i>
          </button>
        </div>
      <% end %>
    </div>
    <%if user_signed_in? %>
      <ul class="user-profil d-flex">
        <p><%= current_user.username %></p>
        <li class="nav-item dropdown">
          <% if current_user.avatar.key.nil? %>
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgsaRe2zqH_BBicvUorUseeTaE4kxPL2FmOQ&usqp=CAU", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <span class='notifications'
            data-controller="notifications"
            data-notifications-flag-value=
            <% result = 0 %>
            <% if current_user %>
              <% Car.where(user_id: current_user.id).each do |i| %>
              <% result += i.bookings.where(status: 'pending_payment').count %>
              <% end %>
              <%= result %>
            <% else %>
            <%= 0 %>
            <% end %>><%= result %>
          </span>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Mes véhicules", dashboard_my_car_path, class: "dropdown-item" %>
            <%= link_to "Mes reservations", dashboard_booking_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method:'delete', class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    <% else %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="nav-buttons d-flex justify-content-between">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link signup" %>
          <%= link_to "Log in", user_session_path, class: "nav-link login" %>
        </div>
      </div>
    <% end %>
  </div>
</div>